### ISSUE TITLE
Number of novel classes

### ISSUE THREAD

**Issue by devinxzhang** [nayeemrizve/TRSSL#1]
Hello!

I am interested in your paper. I would like to consult that in your paper, you claimed the number of novel classes does not need to be known in advance. However, I noticed that in your code, when you defined a network, the dimension of the output of the network was exactly the same as the total number of classes of the dataset. For example, CIFAR-10 has an output dimension of 10. I am wondering if you have considered the case that the output dimension of the network is larger than the number of all classes? 

Thanks!

**Comment by nayeemrizve** [comment]
Hi,

Thank you for going through our work. We did consider the cases when the estimated number of classes is greater than the actual number of classes in the dataset. For reference, you can look at Figure 3 of the main text. However, it's true that the version of the code we put online can only handle the exact number of classes. It can be easily modifiable by taking the no_class as a parameter instead of a fixed predefined value and taking no_seen (number of seen classes) as an argument instead of determining it from the percentage of novel classes as done at https://github.com/nayeemrizve/TRSSL/blob/main/train.py#L107. Hopefully, this answers your question.
